# Generated by Django 6.0.4 on 2026-09-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_encuestaarchivo_encuesta_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
