# Generated by Django 6.0.4 on 2026-09-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_encuesta_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encuesta',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='encuesta',
            name='fechaCreacion',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='fechaVencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
