# Generated by Django 6.0.4 on 2026-09-02 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_remove_encuesta_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestaencuesta',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuestas_respondidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='dirigido',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('Ejecutivo', 'Ejecutivo'), ('Crédito', 'Crédito'), ('Jurídico', 'Jurídico'), ('Sistemas', 'Sistemas')], default='Ejecutivo', max_length=30),
        ),
        migrations.DeleteModel(
            name='Empleado',
        ),
    ]
