# Generated by Django 6.0.4 on 2026-09-03 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_alter_respuestaencuesta_empleado_encuesta_dirigido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='es_correcta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='puntos',
            field=models.IntegerField(default=0),
        ),
    ]
