# Generated by Django 6.0.4 on 2026-09-03 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_pregunta_es_correcta_pregunta_puntos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='es_correcta',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='puntos',
        ),
        migrations.AddField(
            model_name='opcionrespuesta',
            name='es_correcta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opcionrespuesta',
            name='puntos',
            field=models.IntegerField(default=0),
        ),
    ]
