# Generated by Django 6.0.4 on 2026-09-03 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_remove_pregunta_es_correcta_remove_pregunta_puntos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuestaarchivo',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='archivos_encuesta/'),
        ),
    ]
