# Generated by Django 6.0.4 on 2026-09-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_alter_encuestaarchivo_archivo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='respuestaencuesta',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='maxIntentos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='respuestaencuesta',
            name='intento',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='respuestaencuesta',
            name='puntuacion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='respuestaencuesta',
            constraint=models.UniqueConstraint(fields=('encuesta', 'empleado', 'intento'), name='unique_encuesta_empleado_intento'),
        ),
    ]
