# Generated by Django 6.0.4 on 2026-09-14 19:10

import db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_alter_respuestaencuesta_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opcionrespuesta',
            options={'ordering': ['orden', 'id']},
        ),
        migrations.AlterModelOptions(
            name='pregunta',
            options={'ordering': ['orden', 'id']},
        ),
        migrations.AddField(
            model_name='detallerespuesta',
            name='usuarios_seleccionados',
            field=models.ManyToManyField(blank=True, related_name='seleccionado_en_respuestas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opcionrespuesta',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='usuarios_opciones',
            field=models.ManyToManyField(blank=True, related_name='preguntas_como_opcion', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios seleccionables'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='maxIntentos',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='preguntas/', validators=[db.models.validar_tamano_imagen]),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='tipo',
            field=models.CharField(choices=[('OPCION_MULTIPLE', 'Opción Múltiple'), ('TEXTO', 'Texto Libre'), ('USUARIO_UNICO', 'Selección de Usuario (uno)'), ('USUARIO_MULTIPLE', 'Selección de Usuarios (varios)')], default='OPCION_MULTIPLE', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='detallerespuesta',
            constraint=models.UniqueConstraint(fields=('respuesta_encuesta', 'pregunta'), name='unique_respuesta_por_pregunta'),
        ),
    ]
