# Generated by Django 6.0.4 on 2026-09-21 15:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_alter_opcionrespuesta_options_alter_pregunta_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='dirigido',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
