# Generated by Django 6.0.4 on 2026-09-21 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_alter_encuesta_dirigido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encuestas_creadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
